version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: genesis_api_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8012:8000
    env_file:
      - .env/.dev
    depends_on:
      - redis

  redis:
    image: redis:6-alpine

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: genesis_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env/.dev
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    image: genesis_celery_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - .env/.dev
    ports:
      - 5558:5555
    depends_on:
      - redis
