"""empty message

Revision ID: d58048f41d27
Revises: 96a7dd19d333
Create Date: 2023-02-09 10:49:13.911228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58048f41d27'
down_revision = '96a7dd19d333'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
